// <auto-generated />
using MalaDireta.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MalaDireta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230810114850_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("ClienteEndereco", b =>
                {
                    b.Property<int>("LocaisEnderecoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentesClienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocaisEnderecoId", "ResidentesClienteId");

                    b.HasIndex("ResidentesClienteId");

                    b.ToTable("ClienteEndereco");
                });

            modelBuilder.Entity("MalaDireta.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MalaDireta.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CEP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EnderecoId");

                    b.ToTable("Enderecoes");
                });

            modelBuilder.Entity("ClienteEndereco", b =>
                {
                    b.HasOne("MalaDireta.Models.Endereco", null)
                        .WithMany()
                        .HasForeignKey("LocaisEnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MalaDireta.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ResidentesClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
